cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
    path('submit/', views.submit, name='cart_submit'),
    path('quotation/', views.quotation, name='cart_quotation'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product
from .cart import Cart

# Create your views here.

def cart_summary(request):
    cart = Cart(request)
    return render(request, 'cart/summary.html', {'cart': cart})

def submit(request):
    return render(request, 'cart/submit.html')

def quotation(request):
    cart = Cart(request)
    return render(request, 'cart/quotation.html', {'cart': cart})

def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)

        cartqty = cart.__len__()
        response = JsonResponse({'qty': cartqty})
        return response
    
def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'delete':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)

        cartqty = cart.__len__()
        carttotal = cart.get_total_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttotal})
        return response
    
def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'update':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=product_qty)

        basketqty = cart.__len__()
        baskettotal = cart.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

templates/cart/quotation.html
{% extends "../base.html" %} 
{% load static %}

{% block title %}Quotation Form{% endblock %}
{% block content %}

<div class="container">
    <main>
      <div class="py-5 text-center">
        <img class="d-block mx-auto mb-4" src="{% static "store/images/store_logo.png" %}" alt="" width=150px;height=150px>
        <h2>Quotation Form</h2>
      </div>
  
      <div class="row g-5">
        <div class="col-md-5 col-lg-4 order-md-last">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-primary">Your cart</span>
            <span class="badge bg-primary rounded-pill">
                {% with total_qty=cart|length %}
                {% if total_qty > 0 %}
                  {{ total_qty }}
                {% else %}
                  0
                {% endif %}
              {% endwith %}
            </span>
            {% for item in cart %}
            {% with product=item.product %}
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-sm">
              <div>
                <h6 class="my-0">{{ product.title }}</h6>
                <small class="text-body-secondary">{{ product.description }}</small>
              </div>
              <span class="text-body-secondary">₱{{ product.price }}</span>
            </li>
            {% endwith %}
            {% endfor %}
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (PHP)</span>
              <strong>₱{{cart.get_total_price}}</strong>
            </li>
          </ul>
        </div>
        <div class="col-md-7 col-lg-8">
          <h4 class="mb-3">Billing address</h4>
          <form class="needs-validation" novalidate>
            <div class="row g-3">
              <div class="col-sm-6">
                <label for="firstName" class="form-label">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
  
              <div class="col-sm-6">
                <label for="lastName" class="form-label">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
  
              <div class="col-12">
                <label for="username" class="form-label">Username</label>
                <div class="input-group has-validation">
                  <span class="input-group-text">@</span>
                  <input type="text" class="form-control" id="username" placeholder="Username" required>
                <div class="invalid-feedback">
                    Your username is required.
                  </div>
                </div>
              </div>
  
              <div class="col-12">
                <label for="email" class="form-label">Email <span class="text-body-secondary">(Optional)</span></label>
                <input type="email" class="form-control" id="email" placeholder="you@example.com">
                <div class="invalid-feedback">
                  Please enter a valid email address for shipping updates.
                </div>
              </div>
  
              <div class="col-12">
                <label for="address" class="form-label">Address</label>
                <input type="text" class="form-control" id="address" placeholder="1234 Main St" required>
                <div class="invalid-feedback">
                  Please enter your shipping address.
                </div>
              </div>
  
              <div class="col-12">
                <label for="address2" class="form-label">Address 2 <span class="text-body-secondary">(Optional)</span></label>
                <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
              </div>
  
              <div class="col-md-5">
                <label for="country" class="form-label">Country</label>
                <select class="form-select" id="country" required>
                  <option value="">Choose...</option>
                  <option>Philippines</option>
                </select>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
  
              <div class="col-md-4">
                <label for="state" class="form-label">Province</label>
                <select class="form-select" id="state" required>
                  <option value="">Choose...</option>
                  <option>Metro Manila</option>
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="zip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="zip" placeholder="" required>
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
  
            <hr class="my-4">
  
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="same-address">
              <label class="form-check-label" for="same-address">Shipping address is the same as my billing address</label>
            </div>
  
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="save-info">
              <label class="form-check-label" for="save-info">Save this information for next time</label>
            </div>
  
            <hr class="my-4">
  
            <h4 class="mb-3">Payment</h4>
  
            <div class="my-3">
              <div class="form-check">
                <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked required>
                <label class="form-check-label" for="credit">Credit card</label>
              </div>
              <div class="form-check">
                <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required>
                <label class="form-check-label" for="debit">Debit card</label>
              </div>
            </div>
  
            <div class="row gy-3">
              <div class="col-md-6">
                <label for="cc-name" class="form-label">Name on card</label>
                <input type="text" class="form-control" id="cc-name" placeholder="" required>
                <small class="text-body-secondary">Full name as displayed on card</small>
                <div class="invalid-feedback">
                  Name on card is required
                </div>
              </div>
  
              <div class="col-md-6">
                <label for="cc-number" class="form-label">Credit card number</label>
                <input type="text" class="form-control" id="cc-number" placeholder="" required>
                <div class="invalid-feedback">
                  Credit card number is required
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="cc-expiration" class="form-label">Expiration</label>
                <input type="text" class="form-control" id="cc-expiration" placeholder="" required>
                <div class="invalid-feedback">
                  Expiration date required
                </div>
              </div>
  
              <div class="col-md-3">
                <label for="cc-cvv" class="form-label">CVV</label>
                <input type="text" class="form-control" id="cc-cvv" placeholder="" required>
                <div class="invalid-feedback">
                  Security code required
                </div>
              </div>
            </div>
            <hr class="my-4">
          <a>
            <a class="w-100 btn btn-primary btn-lg" type="submit" href="{% url "cart:cart_submit" %}">Submit quotation</a>
          </a>
        </form>
        </div>
      </div>
    </main>

{% endblock %}

templates/cart/submit.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
Papers and Pens
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "store/index.css" %}" />
{% endblock %}

{% block content %}
<main>
    <section class="py-5 text-center container">
      <div class="row py-lg-3">
        <div class="col-lg-6 col-md-8 mx-auto">
        <img class="img-fluid" alt="" src="{% static "store/images/store_logo.png" %}" width=180px;height=180px>
          <h1 class="h1 fw-bold">Quotation Submitted!</h1>
          <p class="lead text-muted">Expect an email from us regarding an update soon. Thank you!</p>
          <p>
            <a href="/" class="btn btn-primary my-2">Back to Home</a>
          </p>
          </p>
        </div>
      </div>
    </section>

    {% endblock %}

templates/cart/summary.html
{% extends "../base.html" %} 
{% load static %}

{% block title %}Cart Summary{% endblock %}
{% block content %}

<main class="pt-5">
    <div class="container">
      <h1 class="h3">Cart:</h1>
      {% for item in cart %}
      {% with product=item.product %}
      <div data-index="{{product.id}}" class="row mb-4 border product-item">
        <div class="col-md-3 col-lg-2 order-md-first bg-light">
          <img class="img-fluid mx-auto d-block" width="120px" alt="Responsive image" src="{{ product.image.url }}">
        </div>
        <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
          <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
            <h1 class="h5 pt-2">{{ product.title }}</h1>
          </a>
          <div class="border">
            <div class="col border-bottom">
              <div class="row p-3">
                <div class="col-6">{{ product.description }}</div>
                <div class="col-6 text-end"><span class="h6 fw-bold">₱{{ product.price }}</span></div>
              </div>
            </div>
            <div class="col">
              <div class="row p-3">
                <div class="col-12">
                  <label for="select">Quantity</label>
                  <select id="select{{product.id}}">
                    <option value="">1</option>
                    <option value="">2</option>
                    <option value="">3</option>
                    <option value="">4</option>
                  </select>
                  <button type="button" id="update-button" data-index="{{product.id}}"
                    class="btn btn-outline-secondary btn-sm update-button">
                    Update
                  </button>
                  <button type="button" id="delete-button" data-index="{{product.id}}"
                    class="btn btn-outline-secondary btn-sm delete-button">
                    Delete
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
      <div class="col-12 text-end">
        <div class="h6 fw-bold">Sub Total: ₱<div id="subtotal" class="d-inline-flex">{{cart.get_total_price}}</div></div>
      </div>
      {% with total_qty=cart|length %}
      {% if total_qty > 0 %}
      <div class="col-12 text-end">
        <a type="button" role="button" href="{% url "cart:cart_quotation" %}" class="btn btn-outline-secondary">Proceed to Quotation Form</a></div>
      {% else %}
      {% endif %}
    {% endwith %}  
    </div>
  </main>

  <script>
    $(document).on('click', '.delete-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_delete" %}',
        data: {
          productid: $(this).data('index'),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'delete'
        },
        success: function (json) {
          $('.product-item[data-index="' + prodid + '"]').remove();
          document.getElementById("subtotal").innerHTML = json.subtotal;
          document.getElementById("cart-qty").innerHTML = json.qty
        },
        error: function (xhr, errmsg, err) {}
      });
    })

    $(document).on('click', '.update-button', function (e) {
      e.preventDefault();
      var prodid = $(this).data('index');
      $.ajax({
        type: 'POST',
        url: '{% url "cart:cart_update" %}',
        data: {
          productid: $(this).data('index'),
          productqty: $('#select' + prodid + ' option:selected').text(),
          csrfmiddlewaretoken: "{{csrf_token}}",
          action: 'update'
        },
        success: function (json) {
          document.getElementById("cart-qty").innerHTML = json.qty
          document.getElementById("subtotal").innerHTML = json.subtotal
        },
        error: function (xhr, errmsg, err) {}
      });
    })
  </script>

  </script>

  {% endblock %}