cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
    path('submit/', views.submit, name='cart_submit'),
    path('quotation/', views.quotation, name='cart_quotation'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path("item/<slug:slug>", views.product_detail, name="product_detail"),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('all-products', views.all, name='all-products'),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from core import settings

# Create your models here.
class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)
    
class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()


    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)
    
    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title
    

store/views.py
from django.shortcuts import get_object_or_404, render

from datetime import date

from .models import Category, Product

def categories(request):
    return{
        'categories': Category.objects.all
    }

def home(request):
    products = Product.objects.all()
    return render(request, 'index.html',{'products': products})

def all(request):
    products = Product.objects.all()
    return render(request, 'all.html',{'products': products})

def about(request):
    return render(request, 'about.html')

def login(request):
    return render(request, 'login.html')

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/product.html', {'product': product})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'store/category.html', {'category': category, 'products': products})

store/templates/store/category.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
My Store
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "store/index.css" %}" />
{% endblock %}

{% block content %}
<div class="container">
    <div class="pb-3 h5">{{category.name}}</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

  {% for product in products %}

  <div class="col">
    <div class="card shadow-sm">
      <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
      <div class="card-body">
        <p class="card-text">
          <a class="text-dark text-decoration-none" href="{{product.get_absolute_url}}">{{ product.title }}</a>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <small class="text-muted">{{product.description}}</small>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
  {% endblock %}

store/templates/store/product.html
{% extends "base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="container">
  <main class="pt-5">
    <div class="row g-3">
      <div class="col-md-5 col-lg-5 order-md-first bg-light">
        <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
      </div>
      <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
        <h1 class="mb-0 h4">{{ product.title }}</h1>
        <p>{{ product.description}}...</p>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">
              <div class="col-6">{{ product.category }}</div>
              <div class="col-6 text-end"><span class="h4 fw-bold">₱{{ product.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-6">
                <label for="select">Quantity</label>
                <select id="select">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                </select>

              </div>
              <div class="col-6 text-end">
                <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-secondary btn-sm">Add to Cart</button></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

  <script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "cart:cart_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("cart-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
  </script>

  {% endblock %}

store/templates/store/products.html
{% extends "base.html" %}
{% load static %}

{% block title %} 
All My Products
{% endblock %} 

{% block css_files %}
{% endblock %}

{% block content %}
<section id="all-products">
  <h2>My Collected products</h2>

  <ul>
    {% include "store/product.html" %}
    {% include "store/product.html" %}
    {% include "store/product.html" %}
  </ul>
</section>
{% endblock %}