account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (PwdResetConfirmForm, PwdResetForm, UserLoginForm)

app_name = 'account'

urlpatterns = [
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html', form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/', 
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name="account/user/delete_confirm.html"), name='delete_confirmation'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='cart_summary'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
    path('submit/', views.submit, name='cart_submit'),
    path('quotation/', views.quotation, name='cart_quotation'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path("item/<slug:slug>", views.product_detail, name="product_detail"),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('all-products', views.all, name='all-products'),
]

templates/about.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
About Us
{% endblock %} 

{% block content %}

<main>
  
      <div class="p-5 mb-4 bg-body-tertiary rounded-3">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">About Us</h1>
          <p class="text-justify fs-5">Papers and Pens is a family-owned business that sells quality office supplies magically sourced from the Nine Realms. Papers and Pens offers all kinds of paper, writing, and filing products to be used by any person, alien, god, or any cosmic entity out there! All products are magically manufactured from highly renewable and sustainable materials from all the different realms, promoting sustainability and eco-friendliness! Every product is made meticulously with love, passion, and magic, molded from unique designs from Asgardian tradition and Wakandan technology. When using our products you are tapping into the power of the multiverse, accessing different dimensions, and wielding power that matches the infinity stones.</p>
          <p class="text-justify fs-5"></p>
          <p class="text-justify fs-5">As we believe in giving back to the community and promoting positive societal change, 15% of all proceeds go to charitable endeavors and to the restoration of New Asgard.</p>
          <p class="text-justify fs-4 fw-bold">Our Address:</p>
          <p class="text-justify fs-5">0618 Wakanda, Lake Turkana, Marvel Multiverse</p>
          <a class="btn btn-primary btn-lg" type="button" href="/all-products">Shop now!</a>
        </div>
      </div>

{%endblock%}

templates/all.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
Papers and Pens
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "store/index.css" %}" />
{% endblock %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5">All Products</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{product.get_absolute_url}}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">{{product.description}}</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>
  </div>
</main>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
  </script>
</head>

<body>
  <header data-bs-theme="dark">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
        <img class="img-fluid" alt="" src="{% static "store/images/store_logo_alt.png" %}" href="/" height = 120px; width=120px>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Product Types
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="/all-products">All</a></li>
                {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                  <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                </li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <div>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
          <div>
            {% if user.is_authenticated %}
            <a type="button" role="button" href="{% url "account:logout" %}"
                class="btn btn-outline-secondary border-0 basket-btn">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                        class="bi bi-door-closed" viewBox="0 0 16 16">
                        <path
                            d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                        <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                    </svg>
                </div>
                <span class="fs15 fw500">Logout</span>
            </a>
            {% else %}
            <a type="button" role="button" href="{% url "account:login" %}"
                class="btn btn-outline-secondary border-0 basket-btn">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                        class="bi bi-door-closed" viewBox="0 0 16 16">
                        <path
                            d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" />
                        <path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                    </svg>
                </div>
                <span class="fs15 fw500">Login</span>
            </a>
            {% endif %}
            <a type="button" role="button" href="{% url "account:dashboard" %}"
            class="btn btn-outline-secondary border-0 basket-btn">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor"
                    class="bi bi-person" viewBox="0 0 16 16">
                    <path
                        d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                </svg>
            </div>
            <span class="fs15 fw500">Account</span>
          </a>
          </div>
          <div>
            <a type="button" role="button" href="{% url "cart:cart_summary" %}" class="btn btn-outline-secondary border-0 basket-btn">
              <div id="cart-qty" class="d-inline-flex">
              {% with total_qty=cart|length %}
                {% if total_qty > 0 %}
                  {{ total_qty }}
                {% else %}
                  0
                {% endif %}
              {% endwith %}
            </div>
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3"
                viewBox="0 0 16 16">
                <path
                  d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
              </svg>
              Cart
            </a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  {% block content %}
  {% endblock %}
  <footer class="container py-5 footer">
    <hr>
    <div class="row pt-4">
        <div class="col-12 col-md">
          <img class="img-fluid" alt="" src="{% static "store/images/store_logo.png" %}" width=100px;height=100px viewBox="0 0 16 16">
                <path
                    d="M8 0a1 1 0 0 1 1 1v5.268l4.562-2.634a1 1 0 1 1 1 1.732L10 8l4.562 2.634a1 1 0 1 1-1 1.732L9 9.732V15a1 1 0 1 1-2 0V9.732l-4.562 2.634a1 1 0 1 1-1-1.732L6 8 1.438 5.366a1 1 0 0 1 1-1.732L7 6.268V1a1 1 0 0 1 1-1z" />
            </svg>
        </div>
        <div class="col-6 col-md fs15">
            <h5>Filing Supplies</h5>
            <ul class="list-unstyled">
              <li><a class="link-secondary text-decoration-none" href="/shop/filing-supplies">View Products</a></li>
            </ul>
        </div>
        <div class="col-6 col-md fs15">
            <h5>Paper Supplies</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="/shop/paper-supplies">View Products</a></li>
            </ul>
        </div>
        <div class="col-6 col-md fs15">
            <h5>Writing Supplies</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="/shop/writing-supplies">View Products</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled">
                <li><a class="link-secondary text-decoration-none" href="/about">Paper and Pens</a></li>
            </ul>
        </div>
    </div>
</footer>
</body>

</html>

templates/index.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
Papers and Pens
{% endblock %} 

{% block css_files %}
  <link rel="stylesheet" href="{% static "store/index.css" %}" />
{% endblock %}

{% block content %}
<main>
    <section class="py-5 text-center container">
      <div class="row py-lg-3">
        <div class="col-lg-6 col-md-8 mx-auto">
        <img class="img-fluid" alt="" src="{% static "store/images/store_logo.png" %}" width=250px;height=250px>
          <h1 class="h1 fw-bold">Welcome to Papers and Pens!</h1>
          <p class="lead text-muted">Papers and Pens is the store for all your paper, writing, and filing needs! Browse through all our quality and affordable products with just a few clicks.</p>
          <p class="font-weight-bold"><b>WANDA<u>VISION</u></b></p>
          <p class="lead text-muted">Whether you’re a writer, office worker, or everyday hero, our products will definitely make you reach unimaginable heights! </p>
          <p>
            <a href="{% url "account:register" %}" class="btn btn-primary my-2">Register</a>
          </p>
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
  
        <div class="pb-3 h5">All Products</div>
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
  
          {% for product in products %}
  
          <div class="col">
            <div class="card shadow-sm">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body">
                <p class="card-text">
                  <a class="text-dark text-decoration-none" href="{{product.get_absolute_url}}">{{ product.title }}</a>
                </p>
                <div class="d-flex justify-content-between align-items-center">
                  <small class="text-muted">{{product.description}}</small>
                </div>
              </div>
            </div>
          </div>
  
          {% endfor %}
  
        </div>
      </div>
    </div>
  </main>
{% endblock %}

templates/login.html
{% extends "base.html" %} 
{% load static %}

{% block title %} 
Login
{% endblock %} 

{% block content %}

<div class="container">
    <div class="d-flex justify-content-center">
        <form>
            <div class="d-flex justify-content-center">
            <img class="mb-4" src="{% static "store/images/test.png" %}" width=200px;height=200px>
            </div>
            <figure class="text-center">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>
            </figure>

            <div class="form-floating">
                <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>

            <div class="form-check text-start my-3">
                <input class="form-check-input" type="checkbox" value="remember-me" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    Remember me
                </label>
            </div>
            <button class="btn btn-primary w-100 py-2" type="submit">Sign in</button>
        </form>
    <script src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous">
    </script>
</div>
</div>

{% endblock %}